### PR TITLE
Added get subnet prefix function.

### PR DESCRIPTION
**Pull request by tomsim**
Would be nice to have this method.

### CODE REVIEW

**Comment by tomsim** [comment]
Coverage fixed.

**Comment by mlocati** [comment]
What about adding some test case?

**Comment by tomsim** [comment]
> Shouldn't it be `return $this->networkPrefix;`?

Fixed. Shame :(

**Comment by mlocati** [comment]
Don't worry, no problems at all! That's why we should have tests covering as much as possible.

**Comment by tomsim** [comment]
All fixes are done.

**Comment by mlocati** [comment]
Thanks!

**Comment by mlocati** [comment]
Included in [release 1.7.0](https://github.com/mlocati/ip-lib/releases/tag/1.7.0).

**Comment by tomsim** [comment]
Thanks!

**Pull request merged**
