### PR TITLE
Add getSize to RangeInterface

### PR DESCRIPTION
**Pull request by vstelmakh**
In some cases it's useful to know count of IP addresses contained within range. Would be nice to have this functionality provided by the library.

### CODE REVIEW

**Comment by mlocati** [comment]
Very useful, thanks!

**Comment by vstelmakh** [comment]
Forgot to update documentation :facepalm:

**Comment by decadence** [comment]
Can you release this? Because documentation contains this method but code doesn't

**Comment by mlocati** [comment]
Done

**Comment by decadence** [comment]
Thanks!

**Pull request merged**
