### PR TITLE
Add getAddressAtOffset for addresses and ranges

### PR DESCRIPTION
**Pull request by ernix**
Shorthand for integer addition and subtraction (if available).

This patch will also integrate getNextAddress/getPreviousAddress.

I'm sorry to tell you that English is not my main language.  Please inform me if the method name or the testing looks weirdo for you.
(I'll be appreciated if you can revise any of them)

### CODE REVIEW

**Comment by mlocati** [comment]
I'm a bit doubtful about the name `getNextNthAddress`.

@ernix what do you think about renaming it as `getAddressAtOffset`?

**Comment by ernix** [comment]
@mlocati I'm dumb at naming, so I'll follow your instructions.

One thing I concern is the word `offset` looks like implying array-ish objects.  So I would expect `IPLib\Range\*` classes also have the same method returning the `IPLib\Address` object as well. (It should throw some `Out of range` if necessary) :)

**Comment by ernix** [comment]
The fundamental significance of `IPLib\Range\RangeInterface::getAddressAtOffset`, is to provide the way to iterate through ip addresses like following:

~~~php
<?php

require_once 'ip-lib.php';

$range = \IPLib\Range\Pattern::fromString('127.0.0.*');

$i = 0;
while ($address = $range->getAddressAtOffset(++$i)) {
    echo $address->toString() . PHP_EOL;
}
~~~

I think`test/tests/Addresses/AtOffsetTest.php` needs more test cases though. (IPv6 address range, Pattern class, Boundary check, etc)

**Comment by landy2005** [comment]
Hi, @mlocati can you look into this "killer feature"? :)

**Comment by mlocati** [comment]
@ernix what about https://github.com/mlocati/ip-lib/pull/60/commits/7149031299fb4ad294e3bab626670cee32fcfe80 (included in this PR)?

**Pull request merged**
