### PR TITLE
return long string of ipv4 address if parameter is present

### PR DESCRIPTION
**Pull request by henry-spanka**
I came across the problem that when I get the long string representation of a IPv4 subnet with `$subnet->toString(true)` it calls the toString method on the IPv4 Address object, however it's still returning the short compacted address and not the long one requested. This causes issue if database operations and comparisons rely on this.

### CODE REVIEW

**Comment by henry-spanka** [comment]
I guess your tests are wrong as you expect the short version in your tests even when the `$long = true` parameter is present.
I will fix the incorrect tests tomorrow.

**Comment by henry-spanka** [comment]
looks good now :)

**Comment by mlocati** [comment]
@henry-spanka Thank you! I'm going to release a new version

**Comment by henry-spanka** [comment]
Thanks 👍

**Pull request merged**
